// world.js — cave diving (not even once) | MagmaCrunch Media (c) 2026
// The segment timeline, the camera, and the passage the cave leaves you.
//
// COORDINATES. The diver lives in SCREEN space and the cave streams past. That
// is not a shortcut - it is what makes one camera serve both a vertical shaft
// and a horizontal squeeze. The water and the camera move together, so a
// passive diver stays put on screen and no "current" force is needed; and when
// the scroll axis changes at a segment boundary the diver needs no rebasing at
// all, because nothing about the diver was expressed in the old axis.
//
// Only the cave changes meaning. `along` is distance down the passage and
// always increases, even in the ascent - the ascent sets `flip`, which mirrors
// the mapping to the screen rather than running the generator backwards.

/* global CONFIG, SEGMENTS, JUNCTION_MS, Timeline, lerp */

/** Seeded PRNG so the tests can drive the same cave twice. */
function mulberry32(a) {
    return function () {
        a |= 0; a = (a + 0x6D2B79F5) | 0;
        let t = Math.imul(a ^ (a >>> 15), 1 | a);
        t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
        return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
}

const SLICE = 16;      // along-space spacing between passage samples

function World(seed) {
    this.reset(seed);
}

World.prototype.reset = function (seed) {
    const sd = seed === undefined ? 12345 : seed;
    // TWO streams, not one. The passage and its contents are generated by
    // different objects called at different rates, and sharing a stream makes
    // the whole cave depend on how their calls happen to interleave - so the
    // same seed produced a different cave at 60Hz and at 120Hz, and the
    // dt-invariance test failed by 57 air with nothing else wrong.
    this.rng = mulberry32(sd);
    this.entityRng = mulberry32((sd + 0x9e3779b9) | 0);
    this.segIndex = 0;
    this.axis = 'y';
    this.flip = false;
    this.camAlong = 0;
    this.slices = [];
    this.wander = 0;
    this.wanderV = 0;
    this.phase = this.rng() * Math.PI * 2;
    this.junction = 0;          // ms left in a junction chamber
    this.collapseFired = false;
    this.shake = 0;
    this.setAxisFor(SEGMENTS[0]);
    for (let i = 0; i < 60; i++) this.appendSlice(SEGMENTS[0], 0);
};

World.prototype.setAxisFor = function (seg) {
    this.axis = seg.kind === 'squeeze' ? 'x' : 'y';
    this.flip = seg.kind === 'ascent';
    this.crossExtent = this.axis === 'y' ? CONFIG.CANVAS_W : CONFIG.CANVAS_H;
    this.alongExtent = this.axis === 'y' ? CONFIG.CANVAS_H : CONFIG.CANVAS_W;
};

/**
 * Half-width of the passage, in cross-axis pixels.
 *
 * PASSAGE_WIDE/TIGHT are quoted against the 480px cross axis of a shaft, so a
 * squeeze - whose cross axis is the 270px canvas height - scales them down.
 * Without this a "wide" horizontal passage would be taller than the screen and
 * the walls would never appear at all.
 */
World.prototype.passageHalf = function (seg) {
    const base = Timeline.passageWidth(seg) * (this.crossExtent / CONFIG.CANVAS_W);
    if (this.junction > 0) return Math.min(this.crossExtent * 0.46, base * 1.7);
    return base / 2;
};

World.prototype.appendSlice = function (seg, t) {
    const last = this.slices.length ? this.slices[this.slices.length - 1] : null;
    // An empty list restarts at the camera, not at zero - the passage is
    // rebuilt mid-dive whenever the scroll axis changes, and restarting at 0
    // would put every new slice hundreds of pixels behind the diver.
    const s = last ? last.s + SLICE : this.camAlong;
    const half = this.passageHalf(seg);

    // The centreline wanders as a damped random walk over a slow sine. The
    // sine alone is too regular to read as rock; the walk alone drifts into a
    // corner and stays there.
    this.wanderV += (this.rng() - 0.5) * 0.9;
    this.wanderV *= 0.86;
    this.wander += this.wanderV;
    const swing = (this.crossExtent * 0.5 - half) * 0.8;
    this.wander = Math.max(-swing, Math.min(swing, this.wander));
    const sine = Math.sin(this.phase + s * 0.006) * swing * 0.45;

    let center = this.crossExtent / 2 + this.wander * 0.5 + sine;
    const lo = half + 6, hi = this.crossExtent - half - 6;
    center = Math.max(lo, Math.min(hi, center));

    this.slices.push({ s, center, half });
};

/** Passage bounds in cross-axis pixels at an along position. */
World.prototype.boundsAt = function (s) {
    const first = this.slices[0];
    if (!first) return { lo: 0, hi: this.crossExtent, center: this.crossExtent / 2 };
    const i = Math.floor((s - first.s) / SLICE);
    const a = this.slices[Math.max(0, Math.min(this.slices.length - 1, i))];
    const b = this.slices[Math.max(0, Math.min(this.slices.length - 1, i + 1))];
    const f = Math.max(0, Math.min(1, (s - a.s) / SLICE));
    const center = lerp(a.center, b.center, f);
    const half = lerp(a.half, b.half, f);
    return { lo: center - half, hi: center + half, center, half };
};

/** Along position of a point at `screenCoord` along the scroll axis. */
World.prototype.alongAtScreen = function (screenCoord) {
    return this.flip
        ? this.camAlong + (this.alongExtent - screenCoord)
        : this.camAlong + screenCoord;
};

/** Where an along position lands on screen. */
World.prototype.screenOf = function (s) {
    return this.flip ? this.alongExtent - (s - this.camAlong) : s - this.camAlong;
};

/**
 * Advance the camera and the timeline.
 * `f` is the dive fraction, 0..1, taken from the song clock in main.js.
 */
World.prototype.update = function (dt, dtMs, f, sfx) {
    const idx = Timeline.indexAt(f);
    if (idx !== this.segIndex) {
        this.segIndex = idx;
        this.junction = JUNCTION_MS;
        const seg = SEGMENTS[idx];
        // The way back shutting. It is placed on the loudest moment in the
        // track (88.7s), so the boom and the music land together.
        if (seg.collapse && !this.collapseFired) {
            this.collapseFired = true;
            this.shake = 46;
            if (sfx) sfx.collapse();
        }
        this.setAxisFor(seg);
        // The passage MUST be rebuilt here. Slices carry a centre and a half
        // width in cross-axis pixels, and the cross axis is 480 wide in a shaft
        // but 270 in a squeeze - so a slice generated for one reads as nonsense
        // in the other, and the walls land off screen until it retires. The
        // junction chamber is what makes the discontinuity invisible.
        this.slices.length = 0;
        this.wander = 0;
        this.wanderV = 0;
        this.axisChanged = true;
    } else {
        this.axisChanged = false;
    }
    if (this.junction > 0) this.junction -= dtMs;
    if (this.shake > 0) this.shake -= dt;

    const seg = SEGMENTS[this.segIndex];
    // Scroll eases in out of a junction, so the chamber is somewhere you
    // arrive rather than a jolt in the middle of the room.
    const ease = this.junction > 0 ? 0.45 + 0.55 * (1 - this.junction / JUNCTION_MS) : 1;
    this.speed = Timeline.scrollSpeed(seg) * ease;
    this.camAlong += this.speed * dt;

    while (!this.slices.length ||
           this.slices[this.slices.length - 1].s < this.camAlong + this.alongExtent + 160) {
        this.appendSlice(seg, f);
    }
    while (this.slices.length > 4 && this.slices[0].s < this.camAlong - 200) {
        this.slices.shift();
    }
};

/** Clamp the diver to the passage. Returns true if a wall was touched. */
World.prototype.confine = function (player) {
    const alongCoord = this.axis === 'y' ? player.y : player.x;
    const b = this.boundsAt(this.alongAtScreen(alongCoord));
    const crossAxis = this.axis === 'y' ? 'x' : 'y';
    const hitWall = player.clampTo(b.lo, b.hi, crossAxis);
    // The scroll axis is bounded by the screen: the cave behind has closed and
    // the cave ahead has not opened yet.
    if (this.axis === 'y') player.clampTo(10, CONFIG.CANVAS_H - 10, 'y');
    else player.clampTo(10, CONFIG.CANVAS_W - 10, 'x');
    return hitWall;
};

/** Convert an (along, cross) cave position into screen pixels. */
World.prototype.toScreen = function (s, cross) {
    const a = this.screenOf(s);
    return this.axis === 'y' ? { x: cross, y: a } : { x: a, y: cross };
};

// ── Drawing ───────────────────────────────────────────────────────────

World.prototype.draw = function (ctx, t) {
    const C = CONFIG.COLORS;
    const g = ctx.createLinearGradient(0, 0, 0, CONFIG.CANVAS_H);
    g.addColorStop(0, C.water);
    g.addColorStop(1, C.waterDeep);
    ctx.fillStyle = g;
    ctx.fillRect(0, 0, CONFIG.CANVAS_W, CONFIG.CANVAS_H);

    const first = this.slices[0];
    if (!first) return;

    for (let i = 0; i < this.slices.length; i++) {
        const sl = this.slices[i];
        const a = this.screenOf(sl.s);
        if (a < -SLICE * 2 || a > this.alongExtent + SLICE * 2) continue;
        const lo = Math.round(sl.center - sl.half);
        const hi = Math.round(sl.center + sl.half);
        const pos = Math.round(this.flip ? a - SLICE : a);

        if (this.axis === 'y') {
            ctx.fillStyle = C.rock;
            ctx.fillRect(0, pos, lo, SLICE);
            ctx.fillRect(hi, pos, CONFIG.CANVAS_W - hi, SLICE);
            ctx.fillStyle = C.rockLit;
            ctx.fillRect(lo - 3, pos, 3, SLICE);
            ctx.fillRect(hi, pos, 3, SLICE);
            ctx.fillStyle = C.rockDeep;
            ctx.fillRect(0, pos, Math.max(0, lo - 14), SLICE);
            ctx.fillRect(hi + 14, pos, Math.max(0, CONFIG.CANVAS_W - hi - 14), SLICE);
        } else {
            ctx.fillStyle = C.rock;
            ctx.fillRect(pos, 0, SLICE, lo);
            ctx.fillRect(pos, hi, SLICE, CONFIG.CANVAS_H - hi);
            ctx.fillStyle = C.rockLit;
            ctx.fillRect(pos, lo - 3, SLICE, 3);
            ctx.fillRect(pos, hi, SLICE, 3);
            ctx.fillStyle = C.rockDeep;
            ctx.fillRect(pos, 0, SLICE, Math.max(0, lo - 14));
            ctx.fillRect(pos, hi + 14, SLICE, Math.max(0, CONFIG.CANVAS_H - hi - 14));
        }
    }
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { World, mulberry32, SLICE };
}
