// main.js — The Jovian Humanitarian Conflict | MagmaCrunch Media © 2026
// State machine, loop, music, scoring policy, HUD and modal wiring.
//
// Everything that decides what a thing is *worth* lives here; entities.js only
// reports what happened. That split is what lets the simulation be flown
// headlessly in tests without dragging the scoreboard along with it.

(function () {
    'use strict';

    const canvas = document.getElementById('gameCanvas');
    const ctx = canvas.getContext('2d');

    const STATE = { TITLE: 0, PLAYING: 1, PAUSED: 2, GAME_OVER: 3 };
    let state = STATE.TITLE;

    const player = new Player();
    const world = new World();
    const entities = new Entities();

    let frame = 0;
    let titleFrame = 0;
    let lastTime = 0;

    let score = 0;
    let kills = 0;
    let escorted = 0;
    let lost = 0;
    let strikes = 0;
    let combo = 1;
    let comboTimer = 0;

    let musicReady = false;
    let musicWanted = false;
    let musicMuted = false;
    let musicGen = 0;

    let localScores = [];

    // ── Boot ──────────────────────────────────────────────────────────

    function init() {
        Renderer.bindResize(canvas);
        // Input.init() must run BEFORE bindUI(), or the Space that starts a run
        // is still sitting in justPressed on frame 1 and fires a shot the
        // player never asked for.
        Input.init();
        Input.initTouch(canvas);
        bindUI();
        loadMutePreference();
        updateMusicDisplay();
        // Deliberately not awaited: the track is 2.7MB, and a title screen that
        // waits for it is a title screen that looks broken on a slow line.
        initAudio();
        loadScores();
        requestAnimationFrame(gameLoop);
    }

    // ── Audio ─────────────────────────────────────────────────────────

    async function initAudio() {
        if (typeof AdAudio === 'undefined') return;
        try {
            await AdAudio.init({
                music: {
                    url: CONFIG.MUSIC.URL,
                    volume: CONFIG.MUSIC.VOLUME,
                    fadeIn: CONFIG.MUSIC.FADE_IN,
                },
            });
            // NOT AdAudio.handleVisibility(). Its pause path calls
            // musicSource.stop() without recording a playhead and its resume
            // path calls playMusic(0) — start(0), the top of the track. Every
            // tab-away and back would replay the opening bars. Ducking the
            // gain instead leaves the one source running, so the playhead keeps
            // advancing and coming back is seamless. The fix belongs upstream
            // in @magmacrunch/adenosine-audio; this file cannot carry it, since
            // arcade/shared/adenosine-*.js is generated by
            // `npm run build:adenosine` and hand edits are destroyed.
            document.addEventListener('visibilitychange', () => {
                if (!musicReady) return;
                AdAudio.setMusicMuted(document.hidden || musicMuted, 0.2);
            });
            // Applied before playMusic(), which reads the muted flag to pick
            // its fade target — so a muted run starts silent rather than fading
            // up and being cut off.
            AdAudio.setMusicMuted(musicMuted, 0);
            musicReady = true;
            if (musicWanted) startMusic();
        } catch (e) {
            musicReady = false;
        }
    }

    /**
     * Only ever reached from the keypress that starts a run: a browser will not
     * let an AudioContext leave 'suspended' without a user gesture.
     */
    function startMusic() {
        musicWanted = true;
        if (!musicReady) return;
        musicGen++;
        AdAudio.setMusicVolume(CONFIG.MUSIC.VOLUME, 0.01);
        try {
            AdAudio.playMusic(CONFIG.MUSIC.FADE_IN);
        } catch (e) {
            // A refused context is not worth breaking the run over.
        }
    }

    /**
     * Fade out and stop. The generation counter is why a fast retry is not
     * silenced by the previous run's pending fade — without it, restarting
     * inside FADE_OUT stops the music that just started.
     */
    function stopMusic(fade) {
        musicWanted = false;
        if (!musicReady) return;
        const gen = ++musicGen;
        AdAudio.setMusicVolume(0, fade);
        setTimeout(() => {
            if (gen !== musicGen) return;
            AdAudio.stopMusic();
            AdAudio.setMusicVolume(CONFIG.MUSIC.VOLUME, 0.01);
        }, fade * 1000);
    }

    function loadMutePreference() {
        try {
            musicMuted = localStorage.getItem('jovianMuted') === '1';
        } catch (e) {
            musicMuted = false;
        }
    }

    function toggleMute() {
        musicMuted = !musicMuted;
        if (musicReady) AdAudio.setMusicMuted(musicMuted);
        try {
            localStorage.setItem('jovianMuted', musicMuted ? '1' : '0');
        } catch (e) { /* private mode; the run still works */ }
        updateMusicDisplay();
    }

    function updateMusicDisplay() {
        const el = document.getElementById('musicState');
        if (el) el.textContent = musicMuted ? 'OFF' : 'ON';
    }

    // ── Loop ──────────────────────────────────────────────────────────

    function gameLoop(timestamp) {
        requestAnimationFrame(gameLoop);

        if (state === STATE.TITLE) {
            titleFrame++;
            world.drawTitle(ctx, titleFrame);
            Renderer.vignette(ctx);
            lastTime = timestamp;
            return;
        }

        // dt in 60fps frames: 1.0 at 60Hz, 0.5 at 120Hz. Capped at 2.0 so a
        // long stall does not teleport the rail through a whole wave.
        const dt = lastTime ? Math.min((timestamp - lastTime) / 16.667, 2.0) : 1.0;
        lastTime = timestamp;

        if (state === STATE.PLAYING) update(dt);
        draw();
    }

    function update(dt) {
        frame++;

        const t = Difficulty.at(world.distance);
        const railSpeed = Difficulty.railSpeed(t);

        const fired = player.update(Input.axisX(), Input.axisY(), Input.firing(), dt);
        if (fired) entities.fire(player);

        world.update(player, railSpeed, dt);
        entities.update(player, railSpeed, t, dt);

        resolveEvents();
        updateCombo(dt);
        Renderer.decay(dt);

        if (player.lives <= 0 || strikes >= CONFIG.MAX_STRIKES) gameOver();
    }

    /**
     * Turn what happened into what it is worth.
     *
     * The asymmetry is the game: a kill is worth 100 and a rescue 500, but
     * shooting the thing you were sent to protect costs 1000 and one of three
     * strikes. Restraint is a losing condition, not a scoring preference.
     */
    function resolveEvents() {
        for (const e of entities.drainEvents()) {
            const c = e.contact;
            switch (e.type) {
                case 'hostile-killed':
                    kills++;
                    score += CONFIG.SCORE_HOSTILE * combo;
                    bumpCombo();
                    entities.addPopup(c.x, c.y, c.z, '+' + (CONFIG.SCORE_HOSTILE * combo), CONFIG.COLORS.hudText);
                    break;

                case 'aid-escorted':
                    escorted++;
                    score += CONFIG.SCORE_ESCORT;
                    bumpCombo();
                    entities.addPopup(c.x, c.y, 30, 'SAFE +' + CONFIG.SCORE_ESCORT, CONFIG.COLORS.aid);
                    break;

                case 'aid-lost':
                    lost++;
                    combo = 1;
                    comboTimer = 0;
                    Renderer.addShake(3);
                    entities.addPopup(c.x, c.y, c.z, 'LOST', CONFIG.COLORS.warn);
                    break;

                case 'friendly-fire':
                    strikes++;
                    score += CONFIG.SCORE_FRIENDLY_FIRE;
                    combo = 1;
                    comboTimer = 0;
                    Renderer.addShake(9);
                    Renderer.addFlash(0.85, '255,47,168');
                    entities.addPopup(c.x, c.y, c.z, 'FRIENDLY FIRE', CONFIG.COLORS.warn);
                    break;

                case 'player-hit':
                    if (player.takeHit()) {
                        Renderer.addShake(7);
                        Renderer.addFlash(0.5, '255,255,255');
                        combo = 1;
                        comboTimer = 0;
                    }
                    break;

                default:
                    break;
            }
        }
        updateHud();
    }

    function bumpCombo() {
        combo = Math.min(CONFIG.COMBO_MAX, combo + 1);
        comboTimer = CONFIG.COMBO_WINDOW;
    }

    function updateCombo(dt) {
        if (comboTimer > 0) {
            comboTimer -= dt;
            if (comboTimer <= 0) combo = 1;
        }
    }

    // ── Draw ──────────────────────────────────────────────────────────

    function draw() {
        const off = Renderer.shakeOffset(frame);
        ctx.save();
        ctx.translate(off.x, off.y);

        world.draw(ctx);
        entities.draw(ctx, world.camX, world.camY, frame);
        player.drawReticle(ctx, world.camX, world.camY);
        player.draw(ctx, world.camX, world.camY);

        ctx.restore();

        drawContactStrip(ctx);
        Renderer.vignette(ctx);
        Renderer.flash(ctx);
    }

    /**
     * The contact strip: every live contact as a tick, placed by its lateral
     * position, marked by type.
     *
     * This is identification channel 2, and it exists so a cluttered frame can
     * never hide the answer. It is also the only place a convoy behind a
     * hostile is still visible, which is the case the spawn separation rule
     * cannot cover once drift has moved them.
     */
    function drawContactStrip(ctx) {
        const C = CONFIG.COLORS;
        const W = CONFIG.CANVAS_W;
        const y = 20;

        ctx.fillStyle = 'rgba(5,6,15,0.55)';
        ctx.fillRect(0, y - 5, W, 11);
        ctx.fillStyle = C.hudDim;
        ctx.fillRect(0, y + 5, W, 1);

        for (const c of entities.listContacts()) {
            // Map world x across the strip, and depth to opacity so nearer
            // contacts read as more urgent.
            const px = Math.round(W / 2 + (c.x / CONFIG.SPAWN_X_RANGE) * (W / 2 - 12));
            const near = 1 - Math.min(1, c.z / CONFIG.Z_FAR);
            ctx.globalAlpha = 0.35 + near * 0.65;

            if (c.kind === 'aid') {
                // A cross: readable as a shape, not only as a colour.
                ctx.fillStyle = C.aid;
                ctx.fillRect(px - 3, y - 1, 7, 2);
                ctx.fillRect(px - 1, y - 3, 2, 7);
            } else {
                ctx.fillStyle = C.hostile;
                ctx.beginPath();
                ctx.moveTo(px, y - 3);
                ctx.lineTo(px + 3, y + 3);
                ctx.lineTo(px - 3, y + 3);
                ctx.closePath();
                ctx.fill();
            }
        }
        ctx.globalAlpha = 1;
    }

    // ── HUD ───────────────────────────────────────────────────────────

    function updateHud() {
        setText('scoreDisplay', score.toLocaleString());
        setText('escortDisplay', String(escorted));
        setText('comboDisplay', 'x' + combo);
        renderLives();
        renderStrikes();
    }

    function setText(id, text) {
        const el = document.getElementById(id);
        if (el) el.textContent = text;
    }

    function renderLives() {
        const el = document.getElementById('livesDisplay');
        if (!el) return;
        el.innerHTML = '';
        for (let i = 0; i < CONFIG.MAX_LIVES; i++) {
            const span = document.createElement('span');
            span.className = 'life' + (i < player.lives ? '' : ' spent');
            span.textContent = '▲';
            el.appendChild(span);
        }
    }

    function renderStrikes() {
        const el = document.getElementById('strikeDisplay');
        if (!el) return;
        el.innerHTML = '';
        for (let i = 0; i < CONFIG.MAX_STRIKES; i++) {
            const span = document.createElement('span');
            span.className = 'strike' + (i < strikes ? ' lit' : '');
            span.textContent = '✕';
            el.appendChild(span);
        }
    }

    // ── Run lifecycle ─────────────────────────────────────────────────

    function startGame() {
        player.reset();
        world.reset();
        entities.reset();
        Renderer.reset();

        score = 0; kills = 0; escorted = 0; lost = 0; strikes = 0;
        combo = 1; comboTimer = 0; frame = 0;
        lastTime = 0;

        // The Space that started the run must not survive into frame 1.
        Input.clearJustPressed();

        hide('titleScreen');
        hide('gameOverOverlay');
        show('hud');
        updateHud();

        state = STATE.PLAYING;
        startMusic();
    }

    function gameOver() {
        if (state === STATE.GAME_OVER) return;
        state = STATE.GAME_OVER;
        stopMusic(CONFIG.MUSIC.FADE_OUT);

        setText('finalScore', score.toLocaleString());
        setText('statKills', String(kills));
        setText('statEscorted', String(escorted));
        setText('statLost', String(lost));
        setText('statStrikes', String(strikes));
        setText('finalRank', rank());
        setText('endReason', strikes >= CONFIG.MAX_STRIKES
            ? 'RELIEVED OF COMMAND'
            : 'SHIP LOST');

        renderScores();
        show('gameOverOverlay');
        const input = document.getElementById('initialsInput');
        if (input) { input.value = ''; input.focus(); }
    }

    /**
     * A rank from how the convoys fared, not from the score.
     *
     * Scoring already rewards escorts, but a rank that read only the number
     * would let a big kill count paper over a bad record — and the record is
     * the thing the title is about.
     */
    function rank() {
        const seen = escorted + lost;
        if (strikes >= CONFIG.MAX_STRIKES) return 'COURT-MARTIALLED';
        if (seen === 0) return 'UNTESTED';
        const ratio = escorted / seen;
        if (strikes === 0 && ratio >= 0.95) return 'EXEMPLARY';
        if (ratio >= 0.8) return 'COMMENDED';
        if (ratio >= 0.6) return 'ACCEPTABLE';
        if (ratio >= 0.35) return 'CENSURED';
        return 'NEGLIGENT';
    }

    // ── Scores ────────────────────────────────────────────────────────

    async function loadScores() {
        if (typeof scoreClient === 'undefined') return;
        try {
            localScores = await scoreClient.load('jovian-humanitarian-conflict') || [];
        } catch (e) {
            localScores = [];
        }
    }

    function renderScores() {
        const tbody = document.getElementById('scoresBody');
        if (!tbody) return;
        tbody.innerHTML = '';
        if (!localScores.length) {
            const tr = document.createElement('tr');
            const td = document.createElement('td');
            td.colSpan = 4;
            td.textContent = 'NO RECORDS';
            tr.appendChild(td);
            tbody.appendChild(tr);
            return;
        }
        localScores.slice(0, 10).forEach((s, i) => {
            const tr = document.createElement('tr');
            // Built as nodes rather than innerHTML: initials come back from the
            // score server, and the one place untrusted text meets the DOM is
            // not the place to save four lines.
            [String(i + 1), s.initials || '???', (s.score || 0).toLocaleString(),
                s.escorted != null ? String(s.escorted) : '0'].forEach((text) => {
                const td = document.createElement('td');
                td.textContent = text;
                tr.appendChild(td);
            });
            tbody.appendChild(tr);
        });
    }

    async function submitInitials() {
        const input = document.getElementById('initialsInput');
        if (!input) return;
        const initials = (input.value || 'AAA').toUpperCase().slice(0, 3);

        localScores.push({ initials: initials, score: score, escorted: escorted });
        localScores.sort((a, b) => b.score - a.score);
        localScores = localScores.slice(0, 10);

        if (typeof scoreClient !== 'undefined') {
            try {
                await scoreClient.save('jovian-humanitarian-conflict', initials, score,
                    { escorted: escorted, lost: lost, kills: kills, strikes: strikes });
            } catch (e) { /* the local table still stands */ }
        }
        hide('initialsPrompt');
        renderScores();
    }

    // ── DOM helpers and wiring ────────────────────────────────────────

    function show(id) {
        const el = document.getElementById(id);
        if (el) el.classList.remove('hidden');
    }

    function hide(id) {
        const el = document.getElementById(id);
        if (el) el.classList.add('hidden');
    }

    function togglePause() {
        if (state === STATE.PLAYING) {
            state = STATE.PAUSED;
            show('pauseOverlay');
            if (musicReady) AdAudio.setMusicMuted(true, 0.2);
        } else if (state === STATE.PAUSED) {
            state = STATE.PLAYING;
            // Reset the clock or the paused wall-time arrives as one huge dt.
            lastTime = 0;
            hide('pauseOverlay');
            if (musicReady) AdAudio.setMusicMuted(musicMuted, 0.2);
        }
    }

    function bindUI() {
        // M and P/Escape live here rather than in Input because they must work
        // on the title and game-over screens, where update() is not polling.
        document.addEventListener('keydown', (e) => {
            if (e.code === 'KeyM') { toggleMute(); return; }
            if (e.code === 'Escape' || e.code === 'KeyP') { togglePause(); return; }

            if (state === STATE.TITLE && (e.code === 'Space' || e.code === 'Enter')) {
                e.preventDefault();
                startGame();
                return;
            }
            if (state === STATE.GAME_OVER && e.code === 'Enter') {
                const prompt = document.getElementById('initialsPrompt');
                if (prompt && !prompt.classList.contains('hidden')) submitInitials();
                else startGame();
            }
        });

        // Touch and mouse both start a run: the title screen is the one place
        // a pointer has to work without a keyboard.
        const title = document.getElementById('titleScreen');
        if (title) title.addEventListener('pointerdown', () => {
            if (state === STATE.TITLE) startGame();
        });

        wire('btnStart', startGame);
        wire('btnRestart', startGame);
        wire('btnSubmit', submitInitials);
        wire('btnResume', togglePause);
        wire('btnMute', toggleMute);
        wire('btnCredits', () => show('creditsOverlay'));
        wire('btnCloseCredits', () => hide('creditsOverlay'));
    }

    function wire(id, fn) {
        const el = document.getElementById(id);
        if (el) el.addEventListener('click', (e) => { e.preventDefault(); fn(); });
    }

    init();
})();
