#!/usr/bin/env python3
"""Sync the texastoast playground's embedded engine to the installed package.

tools/texastoast/app.js embeds a copy of texastoast/** so the playground can
run the engine in the browser under Pyodide (against the fake tkinter in
tools/texastoast/tt_tk_shim.py). That copy drifts every time the engine
changes, and a playground running a stale engine is worse than none — it
demonstrates behaviour the installed package no longer has.

This reads the modules from the *installed* texastoast package (so it tracks
whatever `pip install texastoast` gives) and rewrites the generated block in
app.js. Run by .github/workflows/sync-texastoast-playground.yml on a schedule;
run it by hand any time:

    pip install --upgrade texastoast
    python scripts/sync-texastoast-playground.py

Only the region between the BEGIN/END markers is touched. TT_FILES and the
Pyodide directory list are derived from the embedded paths in app.js itself, so
a new submodule needs no change here.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

APP_JS = Path(__file__).resolve().parent.parent / "tools" / "texastoast" / "app.js"

BEGIN = "// BEGIN GENERATED TEXASTOAST FILES"
END = "// END GENERATED TEXASTOAST FILES"

# Nothing to skip today; the whole package imports cleanly under Pyodide
# because texastoast/__init__.py re-exports lazily and the tkinter modules
# resolve against the shim.
SKIP_NAMES: set[str] = set()


def package_dir() -> Path:
    import texastoast

    return Path(texastoast.__path__[0])


def collect(root: Path) -> dict[str, str]:
    files: dict[str, str] = {}
    for path in sorted(root.rglob("*.py")):
        if "__pycache__" in path.parts or path.name in SKIP_NAMES:
            continue
        files[path.relative_to(root).as_posix()] = path.read_text(encoding="utf-8")
    return files


def render(files: dict[str, str]) -> str:
    lines = [
        BEGIN,
        "// Generated by scripts/sync-texastoast-playground.py from the installed",
        "// texastoast package — do not edit by hand.",
        f"// {len(files)} modules",
        "const TT_FILE_CONTENTS = {",
    ]
    for name, source in files.items():
        lines.append(f"  {json.dumps(name)}: {json.dumps(source)},")
    lines.append("};")
    lines.append(END)
    return "\n".join(lines)


def main() -> int:
    try:
        import texastoast
    except ImportError:
        print("error: texastoast is not installed (pip install texastoast)", file=sys.stderr)
        return 1

    if not APP_JS.exists():
        print(f"error: {APP_JS} not found", file=sys.stderr)
        return 1

    files = collect(package_dir())
    if not files:
        print("error: no modules found in the installed package", file=sys.stderr)
        return 1

    app = APP_JS.read_text(encoding="utf-8")
    if BEGIN not in app or END not in app:
        print(f"error: BEGIN/END markers not found in {APP_JS.name}", file=sys.stderr)
        return 1

    head, _, rest = app.partition(BEGIN)
    _, _, tail = rest.partition(END)
    updated = head + render(files) + tail

    version = getattr(texastoast, "__version__", "?")
    if updated == app:
        print(f"unchanged — playground already matches texastoast {version} "
              f"({len(files)} modules)")
        return 0

    APP_JS.write_text(updated, encoding="utf-8", newline="\n")
    print(f"updated — synced playground to texastoast {version} ({len(files)} modules)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
