#!/usr/bin/env python3
"""Sync the magmascript playground's embedded interpreter to the installed package.

ware/magmascript/app.js embeds a copy of magmascript/lang/** so the playground
can run .mgs code in the browser under Pyodide. That copy drifts every time the
language changes — it once fell a whole major version behind (no Asthenosphere)
while the page still advertised it.

This reads the lang modules from the *installed* magmascript package (so it
tracks whatever `pip install magmascript` gives) and rewrites the generated
block in app.js. Run by .github/workflows/sync-magmascript-playground.yml on a
schedule; run it by hand any time:

    pip install --upgrade magmascript
    python scripts/sync-playground.py

Only the region between the BEGIN/END markers is touched. LANG_FILES and the
Pyodide directory list are derived from the embedded paths in app.js itself, so
a new lang submodule needs no change here.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

APP_JS = Path(__file__).resolve().parent.parent / "ware" / "magmascript" / "app.js"

BEGIN = "// BEGIN GENERATED LANG FILES"
END = "// END GENERATED LANG FILES"

# Needs Pygments, which is not in Pyodide and which the playground does not use.
SKIP_NAMES = {"pygments_mgs.py"}


def lang_dir() -> Path:
    import magmascript.lang as lang

    return Path(lang.__path__[0])


def collect(root: Path) -> dict[str, str]:
    files: dict[str, str] = {}
    for path in sorted(root.rglob("*.py")):
        if "__pycache__" in path.parts or path.name in SKIP_NAMES:
            continue
        files[path.relative_to(root).as_posix()] = path.read_text(encoding="utf-8")
    return files


def render(files: dict[str, str]) -> str:
    lines = [
        BEGIN,
        "// Generated by scripts/sync-playground.py from the installed magmascript",
        "// package — do not edit by hand.",
        f"// {len(files)} modules",
        "const LANG_FILE_CONTENTS = {",
    ]
    for name, source in files.items():
        lines.append(f"  {json.dumps(name)}: {json.dumps(source)},")
    lines.append("};")
    lines.append(END)
    return "\n".join(lines)


def main() -> int:
    try:
        import magmascript
    except ImportError:
        print("error: magmascript is not installed (pip install magmascript)", file=sys.stderr)
        return 1

    if not APP_JS.exists():
        print(f"error: {APP_JS} not found", file=sys.stderr)
        return 1

    files = collect(lang_dir())
    if not files:
        print("error: no lang modules found in the installed package", file=sys.stderr)
        return 1

    app = APP_JS.read_text(encoding="utf-8")
    if BEGIN not in app or END not in app:
        print(f"error: BEGIN/END markers not found in {APP_JS.name}", file=sys.stderr)
        return 1

    head, _, rest = app.partition(BEGIN)
    _, _, tail = rest.partition(END)
    updated = head + render(files) + tail

    version = getattr(magmascript, "__version__", "?")
    if updated == app:
        print(f"unchanged — playground already matches magmascript {version} "
              f"({len(files)} modules)")
        return 0

    APP_JS.write_text(updated, encoding="utf-8", newline="\n")
    print(f"updated — synced playground to magmascript {version} ({len(files)} modules)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
