#!/usr/bin/env python3
"""Sync the texastoast playground's embedded engine to the installed package.

ware/texastoast/app.js embeds a copy of texastoast/** so the playground can
run the engine in the browser under Pyodide (against the fake tkinter in
ware/texastoast/tt_tk_shim.py). That copy drifts every time the engine
changes, and a playground running a stale engine is worse than none — it
demonstrates behaviour the installed package no longer has.

This reads the modules from the *installed* texastoast package (so it tracks
whatever `pip install texastoast` gives) and rewrites the generated block in
app.js. Run by .github/workflows/sync-texastoast-playground.yml on a schedule;
run it by hand any time:

    pip install --upgrade texastoast
    python scripts/sync-texastoast-playground.py

Only the region between the BEGIN/END markers is touched. TT_FILES and the
Pyodide directory list are derived from the embedded paths in app.js itself, so
a new submodule needs no change here.

It then points playground.html's app.js?v= stamp at app.js's new digest.
Rewriting app.js without that leaves returning visitors on the cached old
engine, and this script used to do exactly that: the 0.11.2 sync (2026-09-07)
and the 0.11.3 sync (2026-09-15) each left the stamp stale until somebody
restamped it by hand. The pre-commit hook would have caught it, but the
workflow's bot commit never runs hooks. The stamp is checked on every run,
including one where app.js is already current, so a stale stamp heals itself.
"""

from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path

APP_JS = Path(__file__).resolve().parent.parent / "ware" / "texastoast" / "app.js"
PLAYGROUND = APP_JS.with_name("playground.html")

# The one reference to app.js in playground.html, with or without a stamp.
# Anchored on the quote so a hypothetical other-app.js cannot match.
APP_JS_REF_RE = re.compile(r'(["\'])(app\.js)(?:\?v=[^"\']*)?\1')

BEGIN = "// BEGIN GENERATED TEXASTOAST FILES"
END = "// END GENERATED TEXASTOAST FILES"

# Nothing to skip today; the whole package imports cleanly under Pyodide
# because texastoast/__init__.py re-exports lazily and the tkinter modules
# resolve against the shim.
SKIP_NAMES: set[str] = set()


def package_dir() -> Path:
    import texastoast

    return Path(texastoast.__path__[0])


def collect(root: Path) -> dict[str, str]:
    files: dict[str, str] = {}
    for path in sorted(root.rglob("*.py")):
        if "__pycache__" in path.parts or path.name in SKIP_NAMES:
            continue
        files[path.relative_to(root).as_posix()] = path.read_text(encoding="utf-8")
    return files


def render(files: dict[str, str]) -> str:
    lines = [
        BEGIN,
        "// Generated by scripts/sync-texastoast-playground.py from the installed",
        "// texastoast package — do not edit by hand.",
        f"// {len(files)} modules",
        "const TT_FILE_CONTENTS = {",
    ]
    for name, source in files.items():
        lines.append(f"  {json.dumps(name)}: {json.dumps(source)},")
    lines.append("};")
    lines.append(END)
    return "\n".join(lines)


def main() -> int:
    try:
        import texastoast
    except ImportError:
        print("error: texastoast is not installed (pip install texastoast)", file=sys.stderr)
        return 1

    if not APP_JS.exists():
        print(f"error: {APP_JS} not found", file=sys.stderr)
        return 1

    files = collect(package_dir())
    if not files:
        print("error: no modules found in the installed package", file=sys.stderr)
        return 1

    app = APP_JS.read_text(encoding="utf-8")
    if BEGIN not in app or END not in app:
        print(f"error: BEGIN/END markers not found in {APP_JS.name}", file=sys.stderr)
        return 1

    head, _, rest = app.partition(BEGIN)
    _, _, tail = rest.partition(END)
    updated = head + render(files) + tail

    version = getattr(texastoast, "__version__", "?")
    if updated == app:
        print(f"unchanged — playground already matches texastoast {version} "
              f"({len(files)} modules)")
    else:
        APP_JS.write_text(updated, encoding="utf-8", newline="\n")
        print(f"updated — synced playground to texastoast {version} ({len(files)} modules)")

    return stamp_playground()


def app_digest() -> str:
    """First 8 hex of sha256 over app.js with newlines normalised to LF.

    Must agree with digestContent() in scripts/lib/cache-busters.mjs, which
    check-cache-busters.mjs and the pre-commit hook use to judge this stamp.
    Normalising matters because .js is left to each clone's core.autocrlf: the
    same blob is CRLF on Windows and LF on Linux, and a raw-byte hash would
    make a Windows run and a CI run restamp each other forever.
    """
    text = APP_JS.read_bytes().decode("utf-8").replace("\r\n", "\n")
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:8]


def stamp_playground() -> int:
    """Point playground.html's app.js reference at ?v=<app_digest()>."""
    if not PLAYGROUND.exists():
        print(f"error: {PLAYGROUND} not found", file=sys.stderr)
        return 1

    # Bytes in and out, so the file's own line endings survive untouched.
    source = PLAYGROUND.read_bytes().decode("utf-8")
    digest = app_digest()
    stamped, count = APP_JS_REF_RE.subn(
        lambda m: f"{m.group(1)}{m.group(2)}?v={digest}{m.group(1)}", source
    )
    if count != 1:
        print(f"error: expected one app.js reference in {PLAYGROUND.name}, "
              f"found {count}", file=sys.stderr)
        return 1

    if stamped == source:
        print(f"stamp current — {PLAYGROUND.name} loads app.js?v={digest}")
    else:
        PLAYGROUND.write_bytes(stamped.encode("utf-8"))
        print(f"restamped — {PLAYGROUND.name} now loads app.js?v={digest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
