#!/usr/bin/env python3
"""Sync the shared MagmaScript interpreter bundle to the installed package.

ware/shared/mgs-lang-bundle.js embeds a copy of magmascript/lang/** so browser
playgrounds can run .mgs code under Pyodide. That copy drifts every time the
language changes — it once fell a whole major version behind (no Asthenosphere)
while the page still advertised it.

Two pages consume the bundle: ware/magmascript/ (the language playground) and
ware/crunch-c/ (the C-memory course). Both import it as an ES module, so the
interpreter is embedded once in this repo, not once per page.

This reads the lang modules from the *installed* magmascript package (so it
tracks whatever `pip install magmascript` gives), rewrites the generated block
in the bundle, and re-stamps the `?v=` cache-buster on each consumer's import
specifier. That stamp matters: a bare module import carries no cache-buster, so
without it a returning visitor keeps running the previous release's interpreter.

Run by .github/workflows/sync-magmascript-playground.yml on a schedule; run it
by hand any time:

    pip install --upgrade magmascript
    python scripts/sync-playground.py

Only the region between the BEGIN/END markers is touched, plus the one import
line in each consumer. LANG_FILES and the Pyodide directory list are derived
from the embedded paths in the bundle itself, so a new lang submodule needs no
change here.
"""

from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BUNDLE = ROOT / "ware" / "shared" / "mgs-lang-bundle.js"

# Every page that imports the bundle. Each must contain an import whose
# specifier ends in mgs-lang-bundle.js, optionally already carrying a ?v= stamp.
CONSUMERS = (
    ROOT / "ware" / "magmascript" / "app.js",
    ROOT / "ware" / "crunch-c" / "app.js",
)

BEGIN = "// BEGIN GENERATED LANG FILES"
END = "// END GENERATED LANG FILES"

# The bundle's import specifier in a consumer: captures the quote style and the
# path, discarding any ?v= stamp already there so it can be replaced.
IMPORT_RE = re.compile(r'(["\'])([^"\']*mgs-lang-bundle\.js)(?:\?v=[0-9a-f]+)?\1')

# Needs Pygments, which is not in Pyodide and which the playgrounds do not use.
SKIP_NAMES = {"pygments_mgs.py"}


def lang_dir() -> Path:
    import magmascript.lang as lang

    return Path(lang.__path__[0])


def collect(root: Path) -> dict[str, str]:
    files: dict[str, str] = {}
    for path in sorted(root.rglob("*.py")):
        if "__pycache__" in path.parts or path.name in SKIP_NAMES:
            continue
        # macOS AppleDouble sidecars (._foo.py) match *.py but are binary. A
        # PyPI sdist never carries them; an editable install off a Mac-synced
        # checkout does, and decoding one aborts the whole sync.
        if path.name.startswith("._"):
            continue
        files[path.relative_to(root).as_posix()] = path.read_text(encoding="utf-8")
    return files


def render(files: dict[str, str]) -> str:
    lines = [
        BEGIN,
        "// Generated by scripts/sync-playground.py from the installed magmascript",
        "// package — do not edit by hand.",
        f"// {len(files)} modules",
        "export const LANG_FILE_CONTENTS = {",
    ]
    for name, source in files.items():
        lines.append(f"  {json.dumps(name)}: {json.dumps(source)},")
    lines.append("};")
    lines.append(END)
    return "\n".join(lines)


def bundle_header(version: str) -> str:
    return "\n".join(
        [
            "// ============================================================",
            "// MagmaScript interpreter bundle — shared by the ware playgrounds",
            "// ============================================================",
            "// The magmascript/lang/** sources, embedded as strings so Pyodide can",
            "// write them into its virtual filesystem and import them. Consumed by",
            "// ware/magmascript/app.js and ware/crunch-c/app.js.",
            "//",
            f"// Synced to magmascript {version} by scripts/sync-playground.py.",
            "// Regenerate with:  python scripts/sync-playground.py",
            "",
        ]
    )


def write_bundle(files: dict[str, str], version: str) -> bool:
    """Write the bundle. Returns True if its contents changed on disk."""
    existing = BUNDLE.read_text(encoding="utf-8") if BUNDLE.exists() else None

    if existing is None:
        BUNDLE.parent.mkdir(parents=True, exist_ok=True)
        head, tail = bundle_header(version), "\n"
    else:
        head, sep, rest = existing.partition(BEGIN)
        if not sep or END not in rest:
            print(f"error: BEGIN/END markers not found in {BUNDLE.name}", file=sys.stderr)
            raise SystemExit(1)
        _, _, tail = rest.partition(END)

    updated = head + render(files) + tail
    if updated == existing:
        return False

    BUNDLE.write_text(updated, encoding="utf-8", newline="\n")
    return True


def stamp_consumers(digest: str) -> list[Path]:
    """Point every consumer's import at ?v=<digest>. Returns the ones changed."""
    changed: list[Path] = []
    for path in CONSUMERS:
        if not path.exists():
            # A consumer may legitimately not exist yet on an older checkout.
            print(f"note: skipping absent consumer {path.relative_to(ROOT).as_posix()}")
            continue

        source = path.read_text(encoding="utf-8")
        updated, count = IMPORT_RE.subn(
            lambda m: f"{m.group(1)}{m.group(2)}?v={digest}{m.group(1)}", source
        )
        if count == 0:
            print(
                f"error: no mgs-lang-bundle.js import found in "
                f"{path.relative_to(ROOT).as_posix()}",
                file=sys.stderr,
            )
            raise SystemExit(1)

        if updated != source:
            path.write_text(updated, encoding="utf-8", newline="\n")
            changed.append(path)
    return changed


def main() -> int:
    try:
        import magmascript
    except ImportError:
        print("error: magmascript is not installed (pip install magmascript)", file=sys.stderr)
        return 1

    files = collect(lang_dir())
    if not files:
        print("error: no lang modules found in the installed package", file=sys.stderr)
        return 1

    version = getattr(magmascript, "__version__", "?")
    bundle_changed = write_bundle(files, version)

    digest = hashlib.sha256(BUNDLE.read_bytes()).hexdigest()[:8]
    stamped = stamp_consumers(digest)

    if not bundle_changed and not stamped:
        print(f"unchanged — bundle already matches magmascript {version} "
              f"({len(files)} modules)")
        return 0

    if bundle_changed:
        print(f"updated  — synced bundle to magmascript {version} ({len(files)} modules)")
    for path in stamped:
        print(f"stamped  — {path.relative_to(ROOT).as_posix()} -> ?v={digest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
