#!/usr/bin/env node

import { readdirSync, readFileSync } from 'fs';
import { join } from 'path';

const SCORES_DIR = join(import.meta.dirname, '..', 'arcade', 'admin', 'scores');

function loadScores() {
  const games = [];
  for (const fn of readdirSync(SCORES_DIR)) {
    if (!fn.endsWith('.json') || fn === 'backup') continue;
    const data = JSON.parse(readFileSync(join(SCORES_DIR, fn), 'utf8'));
    games.push(data);
  }
  return games;
}

function formatScore(entry) {
  const s = entry.score || entry.totalScore || 0;
  const parts = [s];
  if (entry.level) parts.push(`L${entry.level}`);
  if (entry.difficulty) parts.push(`D${entry.difficulty}`);
  if (entry.time) parts.push(entry.time);
  if (entry.moves) parts.push(`${entry.moves} moves`);
  if (entry.won === false) parts.push('lost');
  return parts.join(' · ');
}

function playerStats(games) {
  const players = {};
  for (const game of games) {
    for (const s of game.scores) {
      const name = s.initials;
      if (!players[name]) players[name] = { total: 0, games: new Set(), bestScores: {} };
      players[name].total++;
      players[name].games.add(game.gameId);
      const best = s.score || s.totalScore || 0;
      if (!players[name].bestScores[game.gameId] || best > players[name].bestScores[game.gameId]) {
        players[name].bestScores[game.gameId] = best;
      }
    }
  }
  return Object.entries(players)
    .sort((a, b) => b[1].total - a[1].total)
    .map(([name, stats]) => ({
      name,
      total: stats.total,
      gameCount: stats.games.size,
    }));
}

function generateReport() {
  const games = loadScores();
  const totalScores = games.reduce((sum, g) => sum + g.scores.length, 0);
  const players = playerStats(games);
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  const lines = [];
  lines.push(`# Weekly High Scores — ${now}`);
  lines.push('');
  lines.push('## Leaderboards');
  lines.push('');

  for (const game of games.sort((a, b) => a.game.localeCompare(b.game))) {
    lines.push(`### ${game.game}`);
    lines.push('');
    lines.push('| Rank | Player | Score |');
    lines.push('|------|--------|-------|');

    const top = game.scores.slice(0, 5);
    for (let i = 0; i < top.length; i++) {
      const s = top[i];
      lines.push(`| ${i + 1} | ${s.initials} | ${formatScore(s)} |`);
    }

    if (game.scores.length === 0) {
      lines.push('| - | No scores yet | - |');
    }

    lines.push('');
  }

  lines.push('## Stats');
  lines.push('');
  lines.push(`- **Games tracked**: ${games.length}`);
  lines.push(`- **Total scores**: ${totalScores}`);

  if (players.length > 0) {
    lines.push(`- **Most active player**: ${players[0].name} (${players[0].total} scores across ${players[0].gameCount} game${players[0].gameCount > 1 ? 's' : ''})`);
  }

  if (players.length > 1) {
    lines.push(`- **Players**: ${players.map(p => p.name).join(', ')}`);
  }

  lines.push('');
  lines.push('---');
  lines.push('*Generated by GitHub Actions*');

  return lines.join('\n');
}

const report = generateReport();

// If run directly, write to stdout
if (process.argv[1] && process.argv[1].endsWith('weekly-scores.mjs')) {
  console.log(report);
}
