#!/usr/bin/env node

import { readdirSync, readFileSync } from 'fs';
import { join } from 'path';

// The repo's arcade/admin/scores is a copy committed long ago. The live
// scores the arcade server writes are in ~/arcade/admin/scores on the Pi, and
// bot-weekly-scores.sh points SCORES_DIR there -- reporting the repo copy would
// publish July's leaderboard every week.
const SCORES_DIR = process.env.SCORES_DIR
  || join(import.meta.dirname, '..', 'arcade', 'admin', 'scores');

// Skips what the live directory really contains besides game boards, each of
// which would otherwise crash the report or put junk in a public post:
//   - a game with no scores yet, stored as a bare [] rather than an object
//   - __probe_<ts>.json, written by a server health probe (initials ZZZ)
// Files without a gameId take it from the file name, as magmascript's report
// did, so a player's games are still counted per game.
function loadScores() {
  const games = [];
  for (const fn of readdirSync(SCORES_DIR)) {
    if (!fn.endsWith('.json') || fn.startsWith('__')) continue;
    const data = JSON.parse(readFileSync(join(SCORES_DIR, fn), 'utf8'));
    if (!data || Array.isArray(data) || !Array.isArray(data.scores)) continue;
    const id = fn.slice(0, -'.json'.length);
    games.push({ ...data, game: data.game || id, gameId: data.gameId || id });
  }
  return games;
}

function formatScore(entry) {
  const s = entry.score || entry.totalScore || 0;
  const parts = [s];
  if (entry.level) parts.push(`L${entry.level}`);
  if (entry.difficulty) parts.push(`D${entry.difficulty}`);
  if (entry.time) parts.push(entry.time);
  if (entry.moves) parts.push(`${entry.moves} moves`);
  if (entry.won === false) parts.push('lost');
  return parts.join(' · ');
}

function playerStats(games) {
  const players = {};
  for (const game of games) {
    for (const s of game.scores) {
      const name = s.initials;
      if (!players[name]) players[name] = { total: 0, games: new Set(), bestScores: {} };
      players[name].total++;
      players[name].games.add(game.gameId);
      const best = s.score || s.totalScore || 0;
      if (!players[name].bestScores[game.gameId] || best > players[name].bestScores[game.gameId]) {
        players[name].bestScores[game.gameId] = best;
      }
    }
  }
  return Object.entries(players)
    .sort((a, b) => b[1].total - a[1].total)
    .map(([name, stats]) => ({
      name,
      total: stats.total,
      gameCount: stats.games.size,
    }));
}

function generateReport() {
  const games = loadScores();
  const totalScores = games.reduce((sum, g) => sum + g.scores.length, 0);
  const players = playerStats(games);
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  const lines = [];
  lines.push(`# Weekly High Scores — ${now}`);
  lines.push('');
  lines.push('## Leaderboards');
  lines.push('');

  for (const game of games.sort((a, b) => a.game.localeCompare(b.game))) {
    lines.push(`### ${game.game}`);
    lines.push('');
    lines.push('| Rank | Player | Score |');
    lines.push('|------|--------|-------|');

    const top = game.scores.slice(0, 5);
    for (let i = 0; i < top.length; i++) {
      const s = top[i];
      lines.push(`| ${i + 1} | ${s.initials} | ${formatScore(s)} |`);
    }

    if (game.scores.length === 0) {
      lines.push('| - | No scores yet | - |');
    }

    lines.push('');
  }

  lines.push('## Stats');
  lines.push('');
  lines.push(`- **Games tracked**: ${games.length}`);
  lines.push(`- **Total scores**: ${totalScores}`);

  if (players.length > 0) {
    lines.push(`- **Most active player**: ${players[0].name} (${players[0].total} scores across ${players[0].gameCount} game${players[0].gameCount > 1 ? 's' : ''})`);
  }

  if (players.length > 1) {
    lines.push(`- **Players**: ${players.map(p => p.name).join(', ')}`);
  }

  lines.push('');
  lines.push('---');
  lines.push('*Generated by the weekly scores bot*');

  return lines.join('\n');
}

function generateDiscordPayload() {
  const games = loadScores();
  const totalScores = games.reduce((sum, g) => sum + g.scores.length, 0);
  const players = playerStats(games);
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  const medals = ['🥇', '🥈', '🥉'];
  const fields = [];

  for (const game of games.sort((a, b) => a.game.localeCompare(b.game))) {
    const top = game.scores.slice(0, 5);
    let value;

    if (top.length === 0) {
      value = '*No scores yet*';
    } else {
      value = top.map((s, i) => {
        const rank = i < 3 ? medals[i] : `${i + 1}.`;
        return `${rank} **${s.initials}** — ${formatScore(s)}`;
      }).join('\n');
    }

    fields.push({ name: game.game, value, inline: true });
  }

  const footerParts = [`${games.length} games`, `${totalScores} scores`];
  if (players.length > 0) {
    footerParts.push(`${players.length} players`);
  }

  return JSON.stringify({
    embeds: [{
      title: `Weekly High Scores — ${now}`,
      fields,
      footer: { text: footerParts.join(' · ') },
      color: 0xFF3D6E,
    }],
  }, null, 2);
}

const isDiscord = process.argv.includes('--discord');
const output = isDiscord ? generateDiscordPayload() : generateReport();

if (process.argv[1] && process.argv[1].endsWith('weekly-scores.mjs')) {
  console.log(output);
}
